# Generated by Django 5.0 on 2023-12-17 14:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hotel.menuitemcat')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_paid', models.BooleanField()),
                ('pay_deadline', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('guests', models.ManyToManyField(blank=True, related_name='reservations', to='hotel.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hotel.floor')),
                ('menu', models.ManyToManyField(to='hotel.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('accommodation', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hotel.floor')),
            ],
        ),
        migrations.CreateModel(
            name='RoomReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reservation')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel.room')),
            ],
            options={
                'unique_together': {('date', 'room_id')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(blank=True, through='hotel.RoomReserve', to='hotel.room'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hotel.role')),
                ('shifts', models.ManyToManyField(to='hotel.shift')),
            ],
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['end_date'], name='hotel_reser_end_dat_dfb5a6_idx'),
        ),
    ]
