# Generated by Django 5.0 on 2024-01-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_guest_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='id',
            new_name='user',
        ),
    ]
