# Generated by Django 5.0 on 2024-01-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rename_room_id_roomreserve_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreserve',
            old_name='reservation_id',
            new_name='reservation',
        ),
    ]
