# Generated by Django 5.0 on 2024-01-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_rename_reservation_id_roomreserve_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='floor_id',
            new_name='floor',
        ),
    ]
