# Generated by Django 5.0 on 2024-01-05 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_rename_floor_id_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(blank=True, default=500, validators=[django.core.validators.MinValueValidator(500)]),
            preserve_default=False,
        ),
    ]
