# Generated by Django 5.0 on 2024-01-05 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(500)]),
        ),
    ]
