# Generated by Django 5.0 on 2024-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='restaurants',
            field=models.ManyToManyField(to='hotel.restaurant'),
        ),
    ]
