# Generated by Django 5.0 on 2024-01-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_rename_role_id_employee_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category_id',
            new_name='category',
        ),
    ]
