# Generated by Django 5.0 on 2024-01-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_rename_category_id_menuitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='floor_id',
            new_name='floor',
        ),
    ]
