# Generated by Django 5.0 on 2024-01-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_rename_floor_id_restaurant_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
